import { ConferenceEvent } from "src/app/interfaces/ConferenceEvent";

export const EVENTS: ConferenceEvent[] = [
    {
        title: 'ISD2024 – Gdańsk, Poland',
        topic: 'Harnessing Opportunities: Reshaping ISD in the post-COVID-19 and Generative AI Era',
        location: 'University of Gdańsk, Sopot Campus, Poland, August 26–28, 2024',
        homepage: {title:'https://isd2024.ug.edu.pl',link:'https://isd2024.ug.edu.pl'},
        isHomePageArchive:false,
    },
    {
        title: 'ISD2023 – Lisbon, Portugal',
        topic: 'Information systems development, organizational aspects and societal trends',
        location: 'Instituto Superior Técnico, Lisbon, Portugal, August 30–September 1, 2023',
        homepage: {title:'https://isd2023.inesc-id.pt/',link:'https://isd2023.inesc-id.pt/'},
        proceedings: [{title:"ISD2023 Proceedings", link:"https://aisel.aisnet.org/isd2014/proceedings2023/"}],
        isHomePageArchive:false,
    },
    {
        title: 'ISD2022 – Cluj-Napoca, Romania',
        topic: 'A.I. for IS development and operations',
        location: 'Babeș-Bolyai University, Cluj-Napoca, Romania, August 31–September 2, 2022',
        homepage: {title:'https://isd2022.conference.ubbcluj.ro/',link:'https://isd2022.conference.ubbcluj.ro/'},
        proceedings: [{title:"ISD2022 Proceedings", link:"https://aisel.aisnet.org/isd2014/proceedings2022/"},
        {title:"Selection of Best Papers, published by Springer", link:"https://link.springer.com/book/10.1007/978-3-031-32418-5"}],
        isHomePageArchive:false,
    },
    {
        title: 'ISD2021 – Valencia, Spain',
        topic: 'Crossing boundaries between Development and Operations in Information Systems (DevOps)',
        location: 'Universitat Politècnica de València, Spain, September 8–10, 2021',
        homepage: {title:'https://isd2020.webs.upv.es/',link:'https://isd2020.webs.upv.es/'},
        proceedings: [{title:"ISD2021 Proceedings", link:"https://aisel.aisnet.org/isd2014/proceedings2021/"},
        {title:"Selection of Best Papers, published by Springer", link:"https://link.springer.com/book/10.1007/978-3-030-95354-6"}],
        isHomePageArchive:false,
    },
    {
        title: 'ISD2019 – Toulon, France',
        topic: 'Information Systems Beyond 2020',
        location: 'Higher Institute for Electronics and Digital Training (ISEN Yncréa Méditerranée), Toulon, France, August 28–30, 2019',
        homepage: {title:'https://isd2019.isen.fr/', link:'https://web.archive.org/web/20220816182745/https://isd2019.isen.fr/'},
        proceedings: [{title:"ISD2019 Proceedings", link:"https://aisel.aisnet.org/isd2014/proceedings2019/"},
        {title:"Selection of Best Papers, published by Springer", link:"https://link.springer.com/book/10.1007/978-3-030-49644-9"}],
        isHomePageArchive:true,
    },
    {
        title: 'ISD2018 – Lund, Sweden',
        topic: 'Designing Digitalization',
        location: 'Lund University, Sweden, August 22–24, 2018',
        homepage: {title:'http://www.isd2018.ics.lu.se/', link:'https://web.archive.org/web/20230425011310/http://www.isd2018.ics.lu.se/'},
        isHomePageArchive:true,
        proceedings: [{title:"ISD2018 Proceedings", link:"https://aisel.aisnet.org/isd2014/proceedings2018/"},
        {title:"Selection of Best Papers, published by Springer", link:"https://www.springer.com/gp/book/9783030229924"}],
    },
    {
        title: 'ISD2017 – Larnaca, Cyprus',
        topic: 'Advances in Methods, Tools and Management',
        location: 'UCLan Cyprus, School of Sciences, Larnaca, Cyprus, September 6–8, 2017',
        homepage: {title:'http://isd2017.uclancyprus.ac.cy/',link:'https://web.archive.org/web/20211203010404/http://isd2017.uclancyprus.ac.cy/'},
        isHomePageArchive:true,
        proceedings: [{title:"ISD2017 Proceedings", link:"https://aisel.aisnet.org/isd2014/proceedings2017/"},
        {title:"Selection of Best Papers, published by Springer", link:"https://www.springer.com/gp/book/9783319748160"}],
    },
    {
        title: 'ISD2016 – Katowice, Poland',
        topic: 'Complexity in Information Systems Development',
        location: 'University of Economics in Katowice, Poland, August 24–26, 2016',
        homepage: {title:'http://www.isd2016.ue.katowice.pl/',link:'http://www.isd2016.ue.katowice.pl/'},
        proceedings: [{title:"ISD2016 Proceedings", link:"https://aisel.aisnet.org/isd2014/proceedings2016/"},
        {title:"Selection of Best Papers, published by Springer", link:"https://www.springer.com/gp/book/9783319525921"}],
        isHomePageArchive:false,
    },
    {
        title: 'ISD2015 – Harbin, China',
        topic: 'Transforming Healthcare through Information Systems',
        location: 'Harbin Institute of Technology, Harbin, China, August 25–27, 2015',
        homepage: {title:'http://isd2015.hit.edu.cn/',link:'https://web.archive.org/web/20150512214717/http://isd2015.hit.edu.cn/'},
        proceedings: [{title:"ISD2015 Proceedings", link:"https://aisel.aisnet.org/isd2014/proceedings2015/"},
        {title:"Selection of Best Papers, published by Springer", link:"https://www.springer.com/gp/book/9783319301327"}],
        isHomePageArchive:true,
    },
    {
        title: 'ISD2014 – Varazdin, Croatia',
        topic: 'Transforming Organisations and Society through Information Systems',
        location: 'University of Zagreb, Faculty of Organization and Informatics, Varazdin, Croatia, September 2–4, 2014',
        homepage: {title:'http://iwt2.org/isd2013/', link:'https://web.archive.org/web/20230327133528/http://iwt2.org/isd2013/'},
        proceedings: [{title:"ISD2015 Proceedings", link:"https://aisel.aisnet.org/isd2014/proceedings/"}],
        isHomePageArchive:true,
    },
    {
        title: 'ISD2013 – Seville, Spain',
        topic: 'Improving Enterprise Communication',
        location: 'University of Seville, Spain, September 2–4, 2013',
        homepage: {title:'http://iwt2.org/isd2013/',link:'https://web.archive.org/web/20230327133528/http://iwt2.org/isd2013/'},
        proceedings: [{title:"ISD2013 Proceedings", link:"https://www.springer.com/us/book/9783319072142"}],
        isHomePageArchive:true,
    },
    {
        title: 'ISD2012 – Prato, Italy',
        topic: 'Building Sustainable Information Systems',
        location: 'Monash University, Prato, Italy, August 29–30, 2012',
        homepage: {title:'http://infotech.monash.edu/research/ISD2012/',link:'https://web.archive.org/web/20160427092148/http://infotech.monash.edu/research/ISD2012/'},
        proceedings: [{title:"ISD2012 Proceedings", link:"https://www.springer.com/gp/book/9781461475392"}],
        isHomePageArchive:true,
    },
    {
        title: 'ISD2011 – Edinburgh, Scotland',
        topic: 'Reflections, Challenges and New Directions',
        location: 'Heriot-Watt University, Edinburgh, Scotland, August 24–26, 2010',
        homepage: {title:'http://www.macs.hw.ac.uk/ISD2011/', link:'https://web.archive.org/web/20170702083759/http://www.macs.hw.ac.uk/ISD2011/'},
        proceedings: [{title:"ISD2011 Proceedings", link:"https://www.springer.com/us/book/9781461449508"}],
        isHomePageArchive:true,
    },
    {
        title: 'ISD2010 – Prague, Czech Republic',
        topic: 'Business Systems and Services: Modelling and Development',
        location: 'Charles University Prague, Czech Republic, August 25–27, 2010',
        homepage: {title:'https://www.ksi.mff.cuni.cz/isd2010',link:'https://web.archive.org/web/20190128145248/http://www.ksi.mff.cuni.cz:80/isd2010/'},
        proceedings: [{title:"ISD2010 Proceedings", link:"https://www.springer.com/us/book/9781441996459"}],
        isHomePageArchive:true,
    },
    {
        title: 'ISD2009 – Nanchang, China',
        topic: 'Challenge of Practice and Theory in Web-based Information Services',
        location: 'Jiangxi University of Finance & Economics, Nanchang, China, September 16–19, 2009',
        homepage: {title:'http://sit.jxufe.edu.cn/isd2009/',link:'https://web.archive.org/web/20091009173808/http://sit.jxufe.edu.cn/isd2009/'},
        proceedings: [{title:"ISD2009 Proceedings", link:"https://www.springer.com/us/book/9781441972057"}],
        isHomePageArchive:true,
    },
    {
        title: 'ISD2008 – Paphos, Cyprus',
        topic: 'Towards a Service-Provision Society',
        location: 'Department of Computer Science, University of Cyprus, August 25–27, 2008',
        homepage: {title:'http://isd2008.cs.ucy.ac.cy/',link:'http://isd2008.cs.ucy.ac.cy/'},
        proceedings: [{title:"ISD2008 Proceedings", link:"https://www.springer.com/us/book/9780387848099"}],
        isHomePageArchive:false,
    },
    {
        title: 'ISD2007 – Galway, Ireland',
        topic: 'Challenges in Practice, Theory and Education',
        location: 'National University of Ireland, Galway, Ireland, August 29–31, 2007',
        homepage: {title:'http://isd2007.nuigalway.ie/', link:'https://web.archive.org/web/20071212095136/http:/isd2007.nuigalway.ie'},
        proceedings: [{title:"ISD2007 Proceedings", link:"https://www.springer.com/gp/book/9780387304038"}],
        isHomePageArchive:true,
    },
    {
        title: 'ISD2006 – Budapest, Hungary',
        topic: 'New Methods and Practices for the Networked Society',
        location: 'Budapest, Hungary, August 31–September 2, 2006',
        proceedings: [{title:"ISD2006 Proceedings", link:"https://www.springer.com/us/book/9780387707600"}],
        isHomePageArchive:false,
    },
    {
        title: 'ISD2005 – Karlstad, Sweden',
        topic: 'Bridging the Gap between Academia and Industry',
        location: 'Karlstad University, Sweden, August 14–17, 2005',
        homepage: {title:'http://www.it.kau.se/isd2005/', link:'https://web.archive.org/web/20060105095130/http://www.it.kau.se/isd2005'},
        proceedings: [{title:"ISD2005 Proceedings", link:"https://www.springer.com/us/book/9780387308340"}],
        isHomePageArchive:true,
    },
    {
        title: 'ISD2004 – Vilnius, Lithuania',
        topic: 'Advances in Theory, Practice and Education',
        location: 'Vilnius Gediminas Technical University, Lithuania, September 9–11, 2004',
        homepage: {title:'http://isl.vtu.lt/isd2004/',link:'https://web.archive.org/web/20050206065146/http://isl.vtu.lt/isd2004/'},
        proceedings: [{title:"ISD2004 Proceedings", link:"https://www.springer.com/la/book/9780387250267"}],
        isHomePageArchive:true,
    },
    {
        title: 'ISD2003 – Melbourne, Australia',
        topic: 'Information systems development, organizational aspects and societal trends',
        location: 'Instituto Superior Técnico, Lisbon, Portugal, August 30–September 1, 2023',
        proceedings: [{title:"ISD2023 Proceedings", link:"https://aisel.aisnet.org/isd2014/proceedings2023/"}],
        isHomePageArchive:false,
    },
    {
        title: 'ISD2002 – Riga, Latvia',
        topic: 'Advances in Methodologies, Components, and Management',
        location: 'Riga Technical University, Latvia, September 12–14, 2002',
        homepage: {title:'http://www.cs.rtu.lv/isd2002/default.asp',link:'https://web.archive.org/web/20030226235621/http://www.cs.rtu.lv/isd2002/default.asp'},
        proceedings: [{title:"ISD2002 Proceedings", link:"https://www.springer.com/us/book/9781461349501"}],
        isHomePageArchive:true,
    },
    {
        title: 'ISD2001 – London, UK',
        topic: 'New Perspectives on Information Systems Development',
        location: 'Royal Holloway, University of London, United Kingdom, September 5–7, 2001',
        homepage: {title:'http://www.rhbnc.ac.uk/%7Euhtm022/isd2001/',link:'https://web.archive.org/web/20020217021744/http://www.rhbnc.ac.uk/~uhtm022/isd2001/'},
        proceedings: [{title:"ISD2001 Proceedings", link:"https://www.springer.com/gp/book/9780306472510"}],
        isHomePageArchive:true,
    },
    {
        title: 'SD2000 – Kristiansand, Norway',
        topic: 'Contemporary Trends in Systems Development',
        location: 'Agder University College, Kristiansand, Norway, August 14–16, 2000',
        proceedings: [{title:"ISD2000 Proceedings", link:"https://www.springer.com/gp/book/9780306466083"}],
        isHomePageArchive:false,
    },
    {
        title: 'ISD1999 – Boise, Idaho, USA',
        topic: 'Systems Development Methods for Databases, Enterprise Modelling, and Workflow Management',
        location: 'Boise State University, Boise, Idaho, USA, August 11–13, 1999',
        proceedings: [{title:"ISD1999 Proceedings", link:"https://www.springer.com/gp/book/9780306462993"}],
        isHomePageArchive:false,
    },
    {
        title: 'ISD1998 – Bled, Slovenia',
        topic: 'Evolution and Challenges in System Development',
        location: 'University of Maribor, Bled, Slovenia, September 21–23, 1998',
        proceedings: [{title:"ISD1998 Proceedings", link:"https://www.springer.com/gp/book/9780306460531"}],
        isHomePageArchive:false,
    },
    {
        title: 'ISD1997 – Boise, Idaho, USA',
        topic: 'Systems Development Methods for the Next Century',
        location: 'Boise State University, Boise, Idaho, USA, August 11–14, 1997',
        proceedings: [{title:"ISD1997 Proceedings", link:"https://www.springer.com/gp/book/9781461377122"}],
        isHomePageArchive:false,
    },
    {
        title: 'ISD1996 – Gdańsk, Poland',
        location: 'University of Gdańsk, Gdańsk, Poland, September 24–26, 1996',
        isHomePageArchive:false,
    },
    {
        title: 'ISD1994 – Bled, Slovenia',
        location: 'University of Maribor, Bled, Slovenia, September 20–22, 1994',
        isHomePageArchive:false,
    },
    {
        title: 'ISD1992 – Sopot, Poland',
        location: 'University of Gdańsk, Sopot Campus, Poland, September, 1992',
        isHomePageArchive:false,
    },
    {
        title: 'ISD1990 – Bled, Slovenia',
        location: 'University of Maribor, Bled, Slovenia, 1990',
        isHomePageArchive:false,
    },
    {
        title: '1988 – Gdańsk, Poland',
        topic: 'Polish-Scandinavian Seminar on Current Trends in ISD',
        location: 'University of Gdańsk, Gdańsk, Poland, 1988',
        isHomePageArchive:false,
    },
];