import { Ticket } from "../interfaces/Ticket";

export const MOCK_TRACKS: Ticket[] = [
    {
        order: 1,
        Fullprice: 500,
        DiscountBool: true,
        DiscountedPrice: 400,
        TicketType: "Presenting author",
        TicketDescription: "for Paper, Poster, or Journal-first Paper",
        DiscountExpiration: new Date(2023, 5, 14),
        AvailableUntil: new Date(2023, 5, 14),
        // Color: "#ade27c",
        Color: "#98FF98",
    },
    {
        order: 2,
        Fullprice: 300,
        DiscountBool: false,
        DiscountedPrice: 300,
        TicketType: "Discounted fee for additional paper",
        TicketDescription: "for Paper, Poster, or Journal-first Paper",
        DiscountExpiration: new Date(2023, 5, 14),
        AvailableUntil: new Date(2023, 5, 14),
        // Color: "#ade27c",
        Color: "#B0E57C",
    },
    {
        order: 3,
        Fullprice: 50,
        DiscountBool: false,
        DiscountedPrice: 300,
        TicketType: "Extra page",
        TicketDescription: "for Paper, Poster, or Journal-first Paper",
        DiscountExpiration: new Date(2023, 5, 14),
        AvailableUntil: new Date(2023, 5, 14),
        // Color: "#ade27c",
        Color: "#ffe4e1",
    },
    {
        order: 4,
        Fullprice: 400,
        DiscountBool: true,
        DiscountedPrice: 300,
        TicketType: "Normal ticket",
        TicketDescription: "Non-presenting participant (including non-presenting authors)",
        DiscountExpiration: new Date(2023, 5, 14),
        AvailableUntil: new Date(2023, 5, 14),
        // Color: "#3498db",
        // Color: "#8CB9BD",
        Color: "#85A7FF",
    },
    {
        order: 5,
        Fullprice: 300,
        DiscountBool: true,
        DiscountedPrice: 200,
        TicketType: "Discouted ticked",
        TicketDescription: "Active AIS members and students Non-presenting participant (including non-presenting authors)",
        DiscountExpiration: new Date(2023, 5, 14),
        AvailableUntil: new Date(2023, 5, 14),
        // Color: "#ade27c",
        Color: "#ECB159",
    }
]